import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img className={styles.img_profile} src="https://media-exp1.licdn.com/dms/image/C4E03AQE1aCQkKfWCHQ/profile-displayphoto-shrink_800_800/0/1579644737769?e=1675296000&v=beta&t=98Dy2W8yZQI8eczWMFxObGYMvAW1ujbiQYBTMT0A644" alt="Girl in a jacket" width="500" height="600" />
        <div className={styles.info_profile}>
          <h1 className={styles.title} data-test={'title-name'}>
            Jon Wilson Colque Limachi
          </h1>
          <h2 className={styles.subtitle} data-test={'subtitle-profession'}>
            Software Engineer
          </h2>
          <p className={styles.aboutme} data-test={'p-aboutme'}>
            I am passionate about the transmission of human knowledge, especially when it is technology. I am methodical, I focus on delivering value, I like teamwork.
            Systems Engineer.
          </p>
        </div>
      </main>
      <footer className={styles.footer}>
        <p>This page is a proof of concept builded with nextjs to use: Plain html and css. Custom domain. AWS Amplify. AWS Route 53. And will be modified to test several concepts. Last updated: 1 DEC 2022.</p>
      </footer>
    </div>
  )
}
